---
AWSTemplateFormatVersion: "2010-09-09"
Description: Module 5 Stack

Parameters:
  UbuntuId:
    Type: String
    Default: ami-052efd3df9dad4825

  KeyPair:
    Type: String
    Default: will.deberry.labs

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: willDeBerry-vpc

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: willDeBerry-subnet
      VpcId: !Ref VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: willDeBerry-ig

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: willDeBerry-rt
      VpcId: !Ref VPC

  Route:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTable

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet

  EC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        IamInstanceProfile:
          Name: !Ref CloudWatchInstanceProfile
        InstanceType: t2.micro
        KeyName: !Ref KeyPair
        Placement:
          Tenancy: default
        SecurityGroupIds:
          - !Ref UbuntuSG
      LaunchTemplateName: willDeBerryLT
      TagSpecifications:
        - ResourceType: launch-template
          Tags:
            - Key: Name
              Value: willDeBerry-launchTemplate

  UbuntuEC2:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          commands:
            apt-update:
              command: 'apt-get update'
            download:
              command: wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb -O /tmp/amazon-cloudwatch-agent.deb
            install:
              command: dpkg -i /tmp/amazon-cloudwatch-agent.deb
            run:
              command: amazon-cloudwatch-agent-ctl -a start
    Properties:
      ImageId: !Ref UbuntuId
      LaunchTemplate:
        LaunchTemplateId: !Ref EC2LaunchTemplate
        Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber
      SubnetId: !Ref Subnet
      Tags:
        - Key: Name
          Value: willDeBerry-ubuntu
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          wget https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz
          python3 -m easy_install --script-dir /opt/aws/bin aws-cfn-bootstrap-py3-latest.tar.gz
          cfn-init -v --stack ${AWS::StackId} --resource EC2Instance --region ${AWS::Region} --configsets config
          cfn-signal -e $? --stack ${AWS::StackId} --resource EC2Instance --region ${AWS::Region

  UbuntuEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref UbuntuEC2
      Tags:
        - Key: Name
          Value: willDeBerry-ubuntu-eip

  UbuntuSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ICMP and SSH
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: Allow ICMP
          FromPort: 8
          IpProtocol: icmp
          ToPort: -1
        - CidrIp: 0.0.0.0/0
          Description: Allow SSH
          FromPort: 22
          IpProtocol: 6
          ToPort: 22
      Tags:
        - Key: Name
          Value: willDeBerry-sg
      VpcId: !Ref VPC

  CloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
      RoleName: willDeBerry-cloudwatch-role

  CloudWatchInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref CloudWatchRole

Outputs:
  UbuntuEC2Id:
    Description: Ubuntu EC2 instance id
    Value: !Ref UbuntuEC2

  UbuntuEipIp:
    Description: The Ubuntu eip ip address
    Value: !GetAtt UbuntuEC2.PublicIp
