---
AWSTemplateFormatVersion: "2010-09-09"
Description:
  "Will DeBerry's IAM User and Policy created by Cloudformation template"

Parameters:
  UserName:
    Default: willDeBerryLabTestUser
    Type: String

Resources:
  WillDeBerryManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: WillDeBerryManagedPolicy
      ManagedPolicyName: willDeBerry-managed-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
            - s3:Get*
            - s3:List*
            - s3-object-lambda:Get*
            - s3-object-lambda:List*
            Resource: "*"

  WillDeBerryManagedUser:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns:
        - !Ref WillDeBerryManagedPolicy
      UserName: !Ref UserName
