---
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: willDeBerry-vpc

  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        us-east-1b
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: willDeBerry-subnet
      VpcId: !Ref VPC

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        us-east-1c
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: willDeBerry-subnet
      VpcId: !Ref VPC

  SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: Allow port 80
          FromPort: 80
          IpProtocol: 6
          ToPort: 80
      Tags:
        - Key: Name
          Value: willDeBerry-sg-http
      VpcId: !Ref VPC

  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: willDeBerry-igw

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref IGW
      VpcId: !Ref VPC

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: willDeBerry-routeTable-1
      VpcId: !Ref VPC

  Route1:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW
      RouteTableId: !Ref RouteTable

  Subnet1RouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet1

  Subnet2RouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet2

Outputs:
  VPCId:
    Description: Id of the VPC
    Value: !Ref VPC
    Export:
      Name: willDeBerry-vpc

  Subnet1Id:
    Description: Id of the subnet
    Value: !Ref Subnet1
    Export:
      Name: willDeBerry-subnet1

  Subnet2Id:
    Description: Id of the subnet
    Value: !Ref Subnet2
    Export:
      Name: willDeBerry-subnet2

  SGId:
    Description: Id of the security group
    Value: !Ref SG
    Export:
      Name: willDeBerry-sg-http
